### ISSUE TITLE
Can't create a task containing an apostrophe

### ISSUE THREAD

**Issue by kleinfelter** [meeech/nirv#1]
When I try to create a task such as "Kevin's Task", nirv fails with a shell error:
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file

The problem is that task.rb does not escape apostrophes in the call to curl.  I hacked around this by making the 'post' method look like this:

  def post payload0
    payload = payload0.sub("'","\'")
    result = `curl -sX POST 'https://api.nirvanahq.com/?api=json&authtoken=#{@token}' -d '#{payload}'`
  end

**Comment by meeech** [comment]
thanks. will roll it into the gem.

**Comment by meeech** [comment]
fix doesn't seem to be working for me. for some reason, sub doesn't seem to be making the substitution. can i ask what version of ruby you are on (even though i know that shouldnt be a problem - sub is sub as far as I can see)

**Comment by meeech** [comment]
went with gsub to entitize the ' from user data
