### ISSUE TITLE
Gem Broken with API Update?

### ISSUE THREAD

**Issue by michaelcaruso** [meeech/nirv#3]
@meeech -  

I have been using this script for a few days (thanks for releasing it).  On Friday night, I noticed that my tasks weren't getting added to my Inbox via the script.  I contacted support at Nirvana and they told me: 

"It would not surprise me if recent api changes might have broken it - just a guess, but timing is right as we pushed a new api version on Friday afternoon (US ET). [...] The change I suspect that was breaking, was the requirement to pass the app version to the api - we are now blocking stale versions of the app that might have been cached - and that includes not passing a version at all I suspect."

I tried revising the gem so that it includes the app version when passing variables to authenticate at the Nirvana servers, but the JSON response I get is an error code 98, "invalid login details".  I can obtain a token, but I cannot add a task.

Can you provide any guidance/help on a possible fix OR what the API is looking for with respect to login details?

Thanks, 
@michaelcaruso

**Comment by meeech** [comment]
Hi Michael,
I'll get this fixed up.

**Comment by michaelcaruso** [comment]
Thanks, @meeech!

**Comment by kleinfelter** [comment]
Sure would be nice if this worked.  It looks like it is still API failure.  The fetch_token routine successfully calls curl, but the call to parser in its last line fails.

**Comment by meeech** [comment]
@kleinfelter Still works for me. Try deleting your ~/.nirvanahq/token file, and then try again. Open a new ticket if its still not working.
thanks
